import React, { useRef } from 'react';
import { X, Printer } from 'lucide-react';
import ThermalReceipt from '../ThermalReceipt';
import { Order, OrderStatus } from '../../types';

interface InvoiceModalProps {
    order: Order | null;
    onClose: () => void;
}

const InvoiceModal: React.FC<InvoiceModalProps> = ({ order, onClose }) => {
    if (!order) return null;

    return (
        <div className="fixed inset-0 z-[5000] bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 animate-fade-in" onClick={onClose}>
            <div className="bg-white w-full max-w-sm rounded-[32px] overflow-hidden shadow-2xl relative animate-scale-in" onClick={e => e.stopPropagation()}>
                {/* Close Button */}
                <button onClick={onClose} className="absolute top-4 right-4 w-10 h-10 bg-slate-100/50 backdrop-blur rounded-full flex items-center justify-center text-slate-500 hover:bg-slate-200 transition-colors z-10 no-print">
                    <X size={20} />
                </button>

                {/* Thermal Receipt Body */}
                <div className="p-4 bg-[#F8FAFC]">
                    <ThermalReceipt order={order} />

                    {/* Action */}
                    <button className="w-full mt-6 py-4 bg-slate-900 text-white rounded-2xl font-black uppercase tracking-widest text-[10px] flex items-center justify-center gap-2 active:scale-95 transition-all shadow-lg no-print" onClick={() => window.print()}>
                        <Printer size={16} /> Print Receipt
                    </button>
                    <p className="text-center text-[9px] font-bold text-slate-400 mt-4 uppercase tracking-wider no-print">Generated by Restro-Solve</p>
                </div>
            </div>
        </div>
    );
};

export default InvoiceModal;
